### ISSUE TITLE
breeze/storage/DefaultArrayValue

### ISSUE THREAD

**Issue by RLily** [OndraFiedler/spark-recommender#2]
I run into an exception below
Exception in thread "main" java.lang.NoClassDefFoundError: breeze/storage/DefaultArrayValue

**Comment by RLily** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: breeze/storage/DefaultArrayValue
    at recommender.KnnRecommender.<init>(KnnRecommender.scala:25)
    at recommender.KnnRecommender.<init>(KnnRecommender.scala:21)
    at cmd.KnnRecommenderFactory$.getRecommender(RecommenderFactoryFromConf.scala:63)
    at cmd.KnnRecommenderFactory$.getRecommender(RecommenderFactoryFromConf.scala:53)
    at recommender.MainHolder$.setUp(MainHolder.scala:32)
    at Boot$delayedInit$body.apply(Boot.scala:15)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at Boot$.main(Boot.scala:9)
    at Boot.main(Boot.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:329)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: breeze.storage.DefaultArrayValue
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 22 more

**Comment by deric** [comment]
How did you try to run the recommender? It looks like Spak jar was not on class path.

**Comment by deric** [comment]
I was able to reproduce the error when trying to run directly the jar file. It could be avoided when `spark-submit` is used (as stated in the README). E.g. if you use Cloudera distribution:

```
/usr/bin/spark-submit {path to jar file}
```
